// default package
// Generated 16 May, 2014 1:31:57 AM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	private UserPrivilage userPrivilage;
	private String userName;
	private String password;
	private String name;

	public User() {
	}

	public User(int userId, String userName) {
		this.userId = userId;
		this.userName = userName;
	}

	public User(int userId, UserPrivilage userPrivilage, String userName,
			String password, String name) {
		this.userId = userId;
		this.userPrivilage = userPrivilage;
		this.userName = userName;
		this.password = password;
		this.name = name;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public UserPrivilage getUserPrivilage() {
		return this.userPrivilage;
	}

	public void setUserPrivilage(UserPrivilage userPrivilage) {
		this.userPrivilage = userPrivilage;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
