package com.onlinekada.model;

// default package
// Generated 17 May, 2014 7:46:31 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class KadaUser implements MasterModel , java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userName;
	private UserPrivilage userPrivilage;
	private int userId;
	private String password;
	private String name;

	public KadaUser() {
	}

	public KadaUser(String userName, int userId) {
		this.userName = userName;
		this.userId = userId;
	}

	public KadaUser(String userName, UserPrivilage userPrivilage, int userId,
			String password, String name) {
		this.userName = userName;
		this.userPrivilage = userPrivilage;
		this.userId = userId;
		this.password = password;
		this.name = name;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public UserPrivilage getUserPrivilage() {
		return this.userPrivilage;
	}

	public void setUserPrivilage(UserPrivilage userPrivilage) {
		this.userPrivilage = userPrivilage;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
